### PR TITLE
Update max-version to upcoming development version

### PR DESCRIPTION
**Pull request by jancborchardt**
The app already works fine with Nextcloud 14, close https://github.com/jancborchardt/unsplash/issues/25

This makes sure it also works on development instances when 14 is out and the version will be 15. Please review @ChristophWurst @auberginepop @newhinton :tada:

### CODE REVIEW

**Comment by jancborchardt** [comment]
@newhinton @marius-wieschollek could you double-check? I would like to do a new release with the included settings. :)

**Comment by marius-wieschollek** [comment]
@jancborchardt Technically this version will include a new feature. Shouldn't the version be raised to 1.2.0 to show this?

**Comment by newhinton** [comment]
@jancborchardt If you wait until the weekend, we could fully integrate the new caching mechanism, so we only need to make one new version. Although i will add more features over time, which will need their own versions, so it wouldn't be that important

**Comment by jancborchardt** [comment]
Increased to 16 right away so it also works for the current server master.

**Comment by jancborchardt** [comment]
@newhinton since Nextcloud 15 is about to be released on Thursday, do you think it would be ok to do a release from current master tomorrow?

**Comment by newhinton** [comment]
@jancborchardt I will take a look at it later, by tomorow morning you will have my answer ;)

**Comment by jancborchardt** [comment]
@newhinton @marius-wieschollek since Nextcloud 15 is about to be released on Thursday, do you think it would be ok to do a release from current master tomorrow?

**Comment by jancborchardt** [comment]
@newhinton thanks! :)

**Comment by newhinton** [comment]
@jancborchardt I have pulled both nc15 and the current master from unsplash, and i dont really see a reason why we should not release. Everything still works as expected

**Comment by jancborchardt** [comment]
> (Althoug it may look interesting at times, because the way nc15 handles the tooltip in the appmenu, it has the main-color as the background instead of the image, this may be an issue we need to look into, but i guess you could see it as a feature for now :D)

Ahhh good point! Could you open an issue for that? I’ll prepare the release then so it’s out for the Nextcloud 15 release tomorrow. :)

**Comment by newhinton** [comment]
@jancborchardt @marius-wieschollek we should discuss the future of this app sometime, since there are multiple issues like @marius-wieschollek stated earlier. Should we open an issue for that, or should we do that somewhere "private" like irc? It would be a good idea to have a plan where this app is heading :D

**Comment by jancborchardt** [comment]
@newhinton @marius-wieschollek let’s open an issue for that, yes! :) I had a busy last few months, and I prefer to keep everything related to this in public channels. And our channel is this Github repo. :)

The release is done by the way! :)
- https://apps.nextcloud.com/apps/unsplash
- https://github.com/jancborchardt/unsplash/releases/tag/v1.1.3 (feel free to adjust description)
- Changes since last release: https://github.com/jancborchardt/unsplash/compare/v1.1.1...master

**Pull request merged**
