### PR TITLE
Custom Unsplash Link

### PR DESCRIPTION
**Pull request by newhinton**
The workaround for getting the nessessary variables is one of the worse things i did here, but with the recent addition of the settings-branch, and my lack of knowledge about the internal workings of the nextcloud i would wait until i refine it further. Also seeing a working example would help me developing this further. 

I would totally understand if this request would be denied :D

### CODE REVIEW

**Comment by newhinton** [comment]
I have added an .htaccess file, so that the apache webserver can treat the .css as an php file. As long as the header is set properly and the php part does not output invalid code, everything works fine 

Im taking a shot at your branch, maybe i'll figure something out :)

**Comment by newhinton** [comment]
@jancborchardt I somehow implemented everything. You can enter the path in themingsettings, you can change the state of the header. 

Only the css of the inputfield is wrong,up to now, i did not find a way to correct it.

The whole thing relies on the .htaccess file. If the server prohibits the usage of local .htaccess, the app just does not work. Gladly nextcloud is prepared for that, and falls back to the normal background or the one set by the theming app. 

I took the freedom and added my name to the copyright, its not really important, but putting a name on it feels good ;) Since i dont have any clue about all that stuff around licenses, feel free to remove it if this creates problems

**Comment by jancborchardt** [comment]
@newhinton awesome, that's so cool! :) Adding your name is fine of course.

I'd like the app to still work without the .htaccess which might not work on all setups as you say. Any way we can do that?

**Comment by newhinton** [comment]
Maybe, that would require the nextcloud to call either a php file directly, or we could rewrite the login.css file when the controller changes any value. The last one would be relatively easy, but at the same time very badly done

**Comment by newhinton** [comment]
Done. Now the app adds a custom link to the layout, where i can manually set the php file, eliminating the call of login.css

**Comment by NiklasEi** [comment]
This would be an awesome feature and seems to be completed. Is there a reason why it hasn't been merged yet?

**Comment by jancborchardt** [comment]
@NiklasEi 2 reasons:
- There's 3 open pull requests which basically do the same thing, with no collaboration between. Cause I'm mainly a designer and not a developer, I need to check what's the best and most standard way to do it. Help is much appreciated ny reviewing the other pull requests and see what is best. :)
- My laptop is not charging correctly at the moment and is in for repair.

**Comment by newhinton** [comment]
I will take a look at it tomorrow, but it looks like @jancborchardt 's pr is obsolete, since this pr incorporates some if not all changes (will confirm tomorrow)

It looks like the other branch is more complex in regards to the menustructure added to it, but does not have all the features we decided to add to this app. maybe i'll be able to merge those two branches together, so that there wont be any overlap.

**Comment by newhinton** [comment]
@jancborchardt After some digging in #18, i have come to a conclusion and i would suggest we deny this pr, in favor of #18 . After that one has been merged, i will add the nessessary changes to the then to be version, so that we have everything from both pr's in the repo. The reason for this slightly complicated way is that i am not sure that my update from the second repo was correctly done, and now the annotations of who wrote the original file is missing. I dont want that.

**Comment by newhinton** [comment]
@jancborchardt I had the idea that the image from unsplash could be tinted with the main color. It would look similar to the owncloud-default-loginimage, is it a thing i should include in this pr after the merge of #18?

**Comment by jancborchardt** [comment]
@newhinton what do you think about https://github.com/jancborchardt/unsplash/pull/16 though? Am not sure about all the changes of pull request #18, especially cause it overwrites some main stuff with German, and other changes.

**Comment by newhinton** [comment]
@jancborchardt 
It depends on what you want to achieve
#16 implements only background on or off (which is fine by itself)
#18 implements a user controlled toggle, where the user can decide if he wants that header or not

From a technical standpoint, they are not similar, since #18 implements both user and adminsettings, but they are both equally clean implemented. (As far as i have seen it, they both use proper codestyles, etc.)

But i cant seem to find anything in german, did i overlook something there?

**Comment by jancborchardt** [comment]
@newhinton thank you so much for that review! Really appreciate that. :)

In that case I would continue with #16, as we only need user settings. The admin has nothing to do with this as it's personal theming.

**Comment by newhinton** [comment]
@jancborchardt  But if you want it to be a user-setting, you would need #18, #16 only implements it as an instance-wide admin setting, not a user one?

**Comment by newhinton** [comment]
@jancborchardt What is the state here?

**Comment by newhinton** [comment]
Closing, because #18 was merged.

**Pull request closed without merging**
