### PR TITLE
Prevent group restriction

### PR DESCRIPTION
**Pull request by MariusBluem**
@jancborchardt 😇

### CODE REVIEW

**Comment by jancborchardt** [comment]
Ah cool! Does this basically fix what has been discussed at https://github.com/jancborchardt/lsd/issues/5 :)

**Comment by MariusBluem** [comment]
I think this should fix this, but in a perfect world an app with the `auth`-tag would not need this separate `prevent_group_restriction`-tag at all ... But lets ask @MorrisJobke about this 😅

**Comment by MorrisJobke** [comment]
Why is it in authentication?!? Please drop it as described in https://github.com/jancborchardt/lsd/issues/5#issuecomment-356973410 An app is always loaded ... only authentication apps are loaded earlier to hook into the authentication system.

**Comment by jancborchardt** [comment]
So both tags could be dropped, right? @mariusbluem want to update the commit?

**Comment by MorrisJobke** [comment]
> So both tags could be dropped, right? @MariusBluem want to update the commit?

Correct - then it should just work ;) And the version number should be updated, so Nextcloud knows of the change ;)

**Comment by MorrisJobke** [comment]
> (To clarify: It is in auth cause back in the day it seemed to be necessary to have it run on the log in page. Or at least when talking with @LukasReschke we added it.)

Ah right ... it doesn't make sense to use this for the login screen. Because on the login screen you are obviously not logged in and thus the group restriction would not make sense. How to restrict the login screen stuff to a group ;) It's per default not in any group. For the lsd app it makes sense to allow group enabling, because there you are in the logged in context and knew about the group memberships.

**Comment by MariusBluem** [comment]
Well ... since LSD does affect the login-screen too, implementation will be very hard xD

**Comment by jancborchardt** [comment]
Dropped the authentication tag in https://github.com/jancborchardt/unsplash/commit/3c6a922bd3b0ad57ede2194f831822e1121c8257 as @MorrisJobke said.

Now of course group restriction is possible, but it makes little sense since whatever happens on the log in screen can not be restricted because it’s not known. Maybe we can set a cookie/localstorage, that’s also what Google kinda does when it already suggests the user.

**Comment by MariusBluem** [comment]
Preventing group restriction still makes sense. Otherwise you provide admins a setting (Group Restriction) which will have no effect at all - bad UX.

**Pull request closed without merging**
