### PR TITLE
Up min-version, add co-authors

### PR DESCRIPTION
**Pull request by jancborchardt**
- Upping the min-version to Nextcloud 14 as discussed in https://github.com/jancborchardt/unsplash/issues/36
- Adding @newhinton & @marius-wieschollek to authors. ;)

Please review and check if you want to add your email address or have a different website displayed (used your Github profile link).

### CODE REVIEW

**Comment by newhinton** [comment]
looks good ;)

**Comment by jancborchardt** [comment]
@marius-wieschollek @newhinton do you also have accounts on the app store so I can add you as co-authors on the app store page at https://apps.nextcloud.com/apps/unsplash ? :)

**Comment by newhinton** [comment]
no, but i guess i should make one, since i have an app that could be releases :D

**Comment by marius-wieschollek** [comment]
I have one, it's `mdw`

**Comment by jancborchardt** [comment]
@newhinton yes, create one :) then tell me and I’ll add you both.

**Pull request merged**
