### PR TITLE
Add French translation

### PR DESCRIPTION
**Pull request by RavengamerSpace**
Here is the French translation.

But I'm not the "pluralForm" because in french, if you want to use the plural form, you generally put a "s" at the end of the word

### CODE REVIEW

**Comment by RavengamerSpace** [comment]
> Looks good based on my limited French knowledge. ;)
> 
> @skjnldsv @daita mind to give it a quick check?

LOL

Well this is more easy for me because I'm French :D

**Comment by skjnldsv** [comment]
@jancborchardt isn't this app on transifex? If so this changes needs to be done there :)

**Comment by jancborchardt** [comment]
@skjnldsv nah it’s not, we’re super grassroots and unorganized. ;)

**Comment by jancborchardt** [comment]
I’m just going to merge this as it seems fine. Any fixes can be done as a follow-up! :)

**Comment by jancborchardt** [comment]
Thanks a lot for your contribution @RavengamerSpace! :) Welcome to Unsplash :tada:

**Comment by RavengamerSpace** [comment]
@jancborchardt Thanks :+1:

**Comment by skjnldsv** [comment]
Thanks for your work @RavengamerSpace :tada:

**Pull request merged**
